"""Local HTTP bridge used by the static frontend.

The production MCP server in this repository uses stdio because Codex and MCP
clients launch it as a child process.  Browser JavaScript cannot speak to that
stdio stream directly, so this module exposes a small localhost-only HTTP
adapter.  The adapter receives frontend prompts, collects read-oriented
AutoForm Agent facts, and returns the same JSON shape that the page already
expects from its `CodexBridge` layer.  The adapter is a visualization support
service; real Codex tool calls continue to enter through
`autoform_agent.mcp_server`.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, Callable

from .coverage import MODULE_COVERAGE
from .paths import discover_installations
from .queue import queue_health_check


DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 4317
MAX_REQUEST_BYTES = 1024 * 1024

Responder = Callable[[dict[str, Any]], dict[str, Any]]


def build_codex_adapter_reply(
    payload: dict[str, Any],
    snapshot: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build the response contract consumed by `frontend/app.js`.

    The name keeps the frontend wording stable, but the response is generated by
    this local AutoForm Agent adapter.  It reports local, read-only facts so the
    page can prove it is connected to Python while the Codex MCP path remains
    the stdio server configured outside the browser.
    """

    prompt = str(payload.get("prompt") or "").strip()
    conversation_id = str(payload.get("conversationId") or "unknown")
    agent_snapshot = snapshot or collect_agent_snapshot()
    tool_count = agent_snapshot["tool_count"]
    install_count = agent_snapshot["install_count"]
    queue_summary = agent_snapshot["queue_summary"]

    prompt_line = prompt if prompt else "空 prompt"
    text = (
        f"本地 HTTP 适配器已收到前端请求，conversationId={conversation_id}。"
        f" 本次 prompt 为：{prompt_line}。"
        f" 已从当前 AutoForm Agent 读取 {install_count} 条安装发现记录、"
        f"{tool_count} 个已登记工具入口，并完成队列状态只读检查。"
        " 这说明浏览器页面已经可以和本地 Python 适配器通信；"
        "真实 Codex 工具调用请通过 stdio MCP 配置进入 autoform_agent.mcp_server。"
    )

    return {
        "role": "assistant",
        "text": text,
        "time": _utc_now(),
        "timeline": [
            {
                "id": "step-discover",
                "title": "发现 AutoForm 安装",
                "detail": f"本地适配器返回 {install_count} 条安装记录",
                "state": "complete",
            },
            {
                "id": "step-parse",
                "title": "读取 Agent 能力",
                "detail": f"模块覆盖矩阵包含 {len(MODULE_COVERAGE)} 个能力域",
                "state": "complete",
            },
            {
                "id": "step-solver",
                "title": "HTTP 请求响应",
                "detail": "POST /codex 已返回前端可渲染的消息和状态",
                "state": "complete",
            },
        ],
        "preview": {
            "phase": "HTTP Connected",
            "title": "autoform_http_codex_adapter",
            "subtitle": "前端请求已到达本地 Python 适配器",
            "solver": "适配器已响应",
            "solverDetail": queue_summary,
            "activeTool": "autoform_http_codex_adapter",
        },
        "metrics": {
            "connection": "HTTP 已连接",
            "tools": str(tool_count),
            "queue": queue_summary,
        },
        "adapter": {
            "name": "autoform-agent-http-bridge",
            "transport": "HTTP",
            "codexSessionAttached": False,
        },
    }


def collect_agent_snapshot() -> dict[str, Any]:
    """Collect small, read-only facts used to prove the adapter is live."""

    installations, install_error = _safe_call(
        lambda: [installation.as_dict() for installation in discover_installations()],
        fallback=[],
    )
    queue_status, queue_error = _safe_call(queue_health_check, fallback={})
    tool_count = sum(len(row.get("tools", [])) for row in MODULE_COVERAGE)

    return {
        "install_count": len(installations),
        "install_error": install_error,
        "queue_status": queue_status,
        "queue_error": queue_error,
        "queue_summary": _queue_summary(queue_status, queue_error),
        "tool_count": tool_count,
    }


def create_server(
    host: str = DEFAULT_HOST,
    port: int = DEFAULT_PORT,
    responder: Responder = build_codex_adapter_reply,
) -> ThreadingHTTPServer:
    """Create a localhost HTTP server without starting its blocking loop."""

    server = ThreadingHTTPServer((host, port), CodexBridgeRequestHandler)
    server.responder = responder  # type: ignore[attr-defined]
    return server


class CodexBridgeRequestHandler(BaseHTTPRequestHandler):
    """Serve `/health` and `/codex` for the static frontend."""

    server_version = "AutoFormAgentHTTPBridge/0.1"

    def do_OPTIONS(self) -> None:
        """Return CORS preflight headers for browser POST requests."""

        self._send_empty(204)

    def do_GET(self) -> None:
        """Expose a small health endpoint for manual checks and tests."""

        if self.path.rstrip("/") not in {"", "/health"}:
            self._send_json({"error": "unknown endpoint"}, status=404)
            return

        self._send_json(
            {
                "ok": True,
                "service": "autoform-agent-http-bridge",
                "codex_endpoint": "/codex",
            }
        )

    def do_POST(self) -> None:
        """Accept frontend prompts on `/codex` and return adapter JSON."""

        if self.path.rstrip("/") != "/codex":
            self._send_json({"error": "unknown endpoint"}, status=404)
            return

        try:
            payload = self._read_json_payload()
            responder: Responder = getattr(self.server, "responder")
            self._send_json(responder(payload))
        except ValueError as exc:
            self._send_json({"error": str(exc)}, status=400)
        except Exception as exc:  # pragma: no cover - defensive boundary
            self._send_json({"error": f"adapter failed: {exc}"}, status=500)

    def log_message(self, format: str, *args: Any) -> None:
        """Keep the bridge quiet during tests and local frontend demos."""

    def _read_json_payload(self) -> dict[str, Any]:
        length_header = self.headers.get("Content-Length")
        if length_header is None:
            return {}

        try:
            length = int(length_header)
        except ValueError as exc:
            raise ValueError("invalid Content-Length header") from exc

        if length > MAX_REQUEST_BYTES:
            raise ValueError("request body is too large")

        raw_body = self.rfile.read(length)
        try:
            parsed = json.loads(raw_body.decode("utf-8") or "{}")
        except json.JSONDecodeError as exc:
            raise ValueError("request body must be valid JSON") from exc

        if not isinstance(parsed, dict):
            raise ValueError("request body must be a JSON object")
        return parsed

    def _send_empty(self, status: int) -> None:
        self.send_response(status)
        self._send_cors_headers()
        self.end_headers()

    def _send_json(self, payload: dict[str, Any], status: int = 200) -> None:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self._send_cors_headers()
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _send_cors_headers(self) -> None:
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")


def run_server(host: str = DEFAULT_HOST, port: int = DEFAULT_PORT) -> None:
    """Start the blocking HTTP bridge loop."""

    server = create_server(host=host, port=port)
    print(f"AutoForm Agent HTTP bridge listening on http://{host}:{port}/codex")
    try:
        server.serve_forever()
    finally:
        server.server_close()


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint used by `python -m autoform_agent.http_bridge`."""

    parser = argparse.ArgumentParser(prog="python -m autoform_agent.http_bridge")
    parser.add_argument("--host", default=DEFAULT_HOST)
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    args = parser.parse_args(argv)

    run_server(host=args.host, port=args.port)
    return 0


def _safe_call(func: Callable[[], Any], fallback: Any) -> tuple[Any, str | None]:
    try:
        return func(), None
    except Exception as exc:  # pragma: no cover - depends on local AutoForm state
        return fallback, str(exc)


def _queue_summary(queue_status: dict[str, Any], error: str | None) -> str:
    if error:
        return "队列状态待检查"

    processes = queue_status.get("processes") if isinstance(queue_status, dict) else None
    if not processes:
        return "队列状态无进程记录"

    running = [item for item in processes if item.get("running")]
    return f"队列进程 {len(running)}/{len(processes)} 运行中"


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


if __name__ == "__main__":
    raise SystemExit(main())
