from pathlib import Path

from autoform_agent.materials import (
    find_duplicate_material_files,
    inspect_material_file,
    install_material_library,
    list_material_libraries,
    material_library_backup_plan,
    plan_material_files,
)
from autoform_agent.paths import AutoFormInstallation


def test_plan_material_files_keeps_material_and_support_files(tmp_path: Path) -> None:
    source = tmp_path / "source"
    (source / "VW").mkdir(parents=True)
    (source / "VW" / "DC04.mat").write_text("mat", encoding="utf-8")
    (source / "VW" / "DC04.mtb").write_text("mtb", encoding="utf-8")
    (source / "VW" / "raw.csv").write_text("csv", encoding="utf-8")
    (source / "VW" / "standard.pdf").write_text("pdf", encoding="utf-8")

    planned = plan_material_files(source)

    assert [item.relative_path.as_posix() for item in planned] == [
        "VW/DC04.mat",
        "VW/DC04.mtb",
        "VW/raw.csv",
    ]


def test_install_material_library_dry_run_and_copy(tmp_path: Path) -> None:
    source = tmp_path / "source"
    target = tmp_path / "target"
    install_root = tmp_path / "AutoForm" / "AFplus" / "R13F"
    (source / "OEM").mkdir(parents=True)
    (source / "OEM" / "steel.mat").write_text("mat", encoding="utf-8")
    (source / "OEM" / "steel.mtb").write_text("mtb", encoding="utf-8")
    install = AutoFormInstallation("AutoForm Forming R13", "13.0.1.02", install_root)

    dry = install_material_library(source, install=install, target_dir=target, dry_run=True)
    assert dry.dry_run is True
    assert len(dry.planned_files) == 2
    assert not target.exists()

    result = install_material_library(source, install=install, target_dir=target)
    assert len(result.copied_files) == 2
    assert (target / "OEM" / "steel.mat").exists()
    assert (target / "OEM" / "steel.mtb").exists()


def test_list_material_libraries_summarizes_top_level_entries(tmp_path: Path) -> None:
    materials = tmp_path / "materials"
    (materials / "OEM").mkdir(parents=True)
    (materials / "OEM" / "steel.mat").write_text("mat", encoding="utf-8")
    (materials / "OEM" / "steel.mtb").write_text("mtb", encoding="utf-8")
    (materials / "OEM" / "raw.csv").write_text("csv", encoding="utf-8")
    (materials / "PriceTable.xml").write_text("prices", encoding="utf-8")
    install = AutoFormInstallation("AutoForm Forming R13", "13.0.1.02", tmp_path / "install")

    libraries = list_material_libraries(install=install, materials_dir=materials)

    assert libraries[0]["name"] == "OEM"
    assert libraries[0]["kind"] == "directory"
    assert libraries[0]["material_count"] == 2
    assert libraries[0]["support_count"] == 1
    assert libraries[1]["name"] == "PriceTable.xml"
    assert libraries[1]["kind"] == "file"


def test_find_duplicate_material_files_groups_by_name_and_size(tmp_path: Path) -> None:
    materials = tmp_path / "materials"
    (materials / "OEM_A").mkdir(parents=True)
    (materials / "OEM_B").mkdir(parents=True)
    (materials / "OEM_A" / "steel.mat").write_text("same", encoding="utf-8")
    (materials / "OEM_B" / "steel.mat").write_text("diff", encoding="utf-8")
    (materials / "OEM_B" / "aluminum.mat").write_text("same", encoding="utf-8")

    duplicates = find_duplicate_material_files(materials_dir=materials)

    assert len(duplicates) == 1
    assert duplicates[0]["count"] == 2
    assert [item["relative_path"] for item in duplicates[0]["files"]] == [
        "OEM_A\\steel.mat",
        "OEM_B\\steel.mat",
    ]


def test_material_library_backup_plan_can_copy(tmp_path: Path) -> None:
    materials = tmp_path / "materials"
    library = materials / "OEM"
    library.mkdir(parents=True)
    (library / "steel.mat").write_text("mat", encoding="utf-8")
    backup_root = tmp_path / "backup"

    dry = material_library_backup_plan(
        "OEM",
        backup_root,
        materials_dir=materials,
        timestamp="20260523_210000",
    )
    assert dry["dry_run"] is True
    assert dry["copied"] is False
    assert dry["summary"]["material_count"] == 1
    assert not backup_root.exists()

    copied = material_library_backup_plan(
        "OEM",
        backup_root,
        materials_dir=materials,
        dry_run=False,
        timestamp="20260523_210000",
    )
    assert copied["copied"] is True
    assert (backup_root / "OEM_20260523_210000" / "steel.mat").exists()


def test_inspect_material_file_reads_mat_structure(tmp_path: Path) -> None:
    material = tmp_path / "steel.mat"
    material.write_text(
        "\n".join(
            [
                "## WARNING: Generated by AutoForm Material Editor",
                "YoungsModulus 210000",
                "PoissonsRatio 0.3",
                "HardeningCurve",
                "  Thickness 1.0",
                "   0 0 100",
                "   1 0.1 120",
            ]
        ),
        encoding="utf-8",
    )

    info = inspect_material_file(material, preview_lines=2, hash_contents=True)

    assert info["format"] == "mat_text"
    assert info["generation_tools"] == ["material_editor"]
    assert info["scalar_properties"]["YoungsModulus"] == "210000"
    assert info["has_hardening_curve"] is True
    assert info["thickness_section_count"] == 1
    assert info["numeric_table_rows"] == 2
    assert len(info["hash_sha256"]) == 64


def test_inspect_material_file_reports_mtb_binary(tmp_path: Path) -> None:
    material = tmp_path / "steel.mtb"
    material.write_bytes(b"\x00\x01AutoForm")

    info = inspect_material_file(material)

    assert info["format"] == "mtb_binary"
    assert info["binary"] is True
    assert info["magic_hex"] == "00014175746f466f726d"
